### ISSUE TITLE
IllegalArgumentException при вызове getPortfolioSync

### ISSUE THREAD

**Issue by rawnvdm** [Tinkoff/invest-api-java-sdk#15]
При запросе портфеля получаю:
```
java.lang.IllegalArgumentException: null
	at java.base/java.util.Currency.getInstance(Currency.java:315) ~[na:na]
	at java.base/java.util.Currency.getInstance(Currency.java:296) ~[na:na]
	at ru.tinkoff.piapi.core.models.Money.fromResponse(Money.java:23) ~[java-sdk-core-1.0-M5.jar:na]
	at ru.tinkoff.piapi.core.models.Position.fromResponse(Position.java:52) ~[java-sdk-core-1.0-M5.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1621) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at ru.tinkoff.piapi.core.models.Portfolio.fromResponse(Portfolio.java:45) ~[java-sdk-core-1.0-M5.jar:na]
	at ru.tinkoff.piapi.core.OperationsService.getPortfolioSync(OperationsService.java:216) ~[java-sdk-core-1.0-M5.jar:na]
```
Возникает из-за того, что в нескольких позициях портфеля не указана валюта. Например, у меня в портфеле есть "figi": "BBG00W7FG4V8", у которого в currentNkd поле "currency": "". Соответственно выбрасывается исключение при следующей проверке:
`
if (currencyCode.length() != 3) {
    throw new IllegalArgumentException();
}
`

**API:** implementation 'ru.tinkoff.piapi:java-sdk-core:1.0-M5'
**Java:** openjdk-17.0.2

**Comment by Silhin** [comment]
Такая же проблема.
При попытке получить весь портфель с помощью метода `.getPortfolioSync()`, выкидывается исключение:
```
Caused by: java.lang.IllegalArgumentException
	at java.base/java.util.Currency.getInstance(Currency.java:317)
	at java.base/java.util.Currency.getInstance(Currency.java:298)
Caused by: java.lang.IllegalArgumentException

	at ru.tinkoff.piapi.core.models.Money.fromResponse(Money.java:23)
	at ru.tinkoff.piapi.core.models.Position.fromResponse(Position.java:52)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at ru.tinkoff.piapi.core.models.Portfolio.fromResponse(Portfolio.java:45)
	at ru.tinkoff.piapi.core.OperationsService.getPortfolioSync(OperationsService.java:216)
```

С помощью Debug выяснил что исключение появляется при создании позиции в методе `fromResponse(@Nonnull PortfolioPosition portfolioPosition)` класса **ru.tinkoff.piapi.core.models.Position**

![image](https://user-images.githubusercontent.com/68598334/161700306-980b96d4-1673-468e-90cc-6a78c2bf0c94.png)

В моем случае в метод передавалась **Акция** _(instumentType = "share")_.
![image](https://user-images.githubusercontent.com/68598334/161701956-7a0e760c-9ea2-45d4-a6da-7690ef0133bf.png)
 

Метод `portfolioPosition.getCurrentNkd()` класса **ru.tinkoff.piapi.contract.v1.PortfolioPosition**, который возвращает НКД _(Накопленный купонный доход)_ инструмента, представлен ниже.
Как видно из скриншота выше - `currentNkd_ = {MoneyValue@7810} ""`

```
  /**
   * <pre>
   * Текущий НКД
   * </pre>
   *
   * <code>.tinkoff.public.invest.api.contract.v1.MoneyValue current_nkd = 6;</code>
   * @return The currentNkd.
   */
  @java.lang.Override
  public ru.tinkoff.piapi.contract.v1.MoneyValue getCurrentNkd() {
    return currentNkd_ == null ? ru.tinkoff.piapi.contract.v1.MoneyValue.getDefaultInstance() : currentNkd_;
  }
```
В результате чего в статический метод `fromResponse(@Nonnull MoneyValue moneyValue)` класса **ru.tinkoff.piapi.core.models.Money** отправляется **currentNkd_ = {MoneyValue@7810} ""**.

```
  public static Money fromResponse(@Nonnull MoneyValue moneyValue) {
    return new Money(
      Currency.getInstance(moneyValue.getCurrency().toUpperCase(Locale.ROOT)),
      MapperUtils.moneyValueToBigDecimal(moneyValue)
    );
  }
```

По итогу в статический метод `getInstance(String currencyCode, int defaultFractionDigits, int numericCode)` класса **java.util.Currency** передается _currencyCode=""_. 

Так как валюты "" по стандарту ISO 4217 нет, выкидывается исключение `IllegalArgumentException`.

**SDK: Oracle OpenJDK version 17.0.2
API: ru.tinkoff.piapi:java-sdk-core:1.0-M5
Gradle: 7.4.1**

**Comment by hondasmx** [comment]
Спасибо за репорт
Завтра сделаем фикс, которые должен исправить проблему. Обновление SDK не потребуется

**Comment by Shemplo** [comment]
Ошибка больше не возникает
