### ISSUE TITLE
Ошибка создания api. не читает свойства файла из config.properties метод defaultChannel

### ISSUE THREAD

**Issue by JohnDarkElf** [Tinkoff/invest-api-java-sdk#36]
собственно выдает ошибку Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: text
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.time.Duration.parse(Duration.java:390)
	at ru.tinkoff.piapi.core.InvestApi.defaultChannel(InvestApi.java:232)
	at ru.tinkoff.piapi.core.InvestApi.defaultChannel(InvestApi.java:258)
	at John.home.bender.Tinkv2.Tinkv2(Tinkv2.java:11)
через debug нашел что просто 
  public static Channel defaultChannel(String token) {
    var target = props.getProperty("ru.tinkoff.piapi.core.api.target");
    return defaultChannel(token, defaultAppName, target);
  }
после строки target = null

**Comment by JohnDarkElf** [comment]
ошибка не в api. classLoader нет тот файл config грузит...
