### ISSUE TITLE
No NameResolverProviders found via ServiceLoader, including for DNS

### ISSUE THREAD

**Issue by GoginArtem** [Tinkoff/invest-api-java-sdk#50]
Добрый день, использую скалу 2.12.12 и когда делаю fat jar, не могу его запустить, т.к. получаю ошибку ниже.
Единственное решение, которое нашел в интернете - решено на уровне grpc библиотеки для java: https://github.com/grpc/grpc-java/issues/2149
Написано, что решено с версии 1.6+, но в текущей SDK используется версия 1.44. Можно ли обновить зависимость? 

```
2023 3:23:45 PM io.grpc.NameResolverRegistry getDefaultRegistry
WARNING: No NameResolverProviders found via ServiceLoader, including for DNS. This is probably due to a broken build. If using ProGuard, check your configuration
java.lang.IllegalArgumentException: cannot find a NameResolver for invest-public-api.tinkoff.ru:443
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:773)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:782)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:662)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:631)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
        at ru.tinkoff.piapi.core.InvestApi.defaultChannel(InvestApi.java:246)
        at ru.tinkoff.piapi.core.InvestApi.defaultChannel(InvestApi.java:252)
        at ru.tinkoff.piapi.core.InvestApi.create(InvestApi.java:119)
        at MainTrader$.<init>(MainTrader.scala:9)
        at MainTrader$.<clinit>(MainTrader.scala)
        at MainTrader.main(MainTrader.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at scala.reflect.internal.util.RichClassLoader$.$anonfun$run$extension$1(ScalaClassLoader.scala:101)
        at scala.reflect.internal.util.RichClassLoader$.run$extension(ScalaClassLoader.scala:36)
        at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:29)
        at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:27)
        at scala.tools.nsc.JarRunner$.run(MainGenericRunner.scala:21)
        at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:36)
        at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:35)
        at scala.tools.nsc.JarRunner$.runAndCatch(MainGenericRunner.scala:21)
        at scala.tools.nsc.JarRunner$.runJar(MainGenericRunner.scala:33)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:79)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:92)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

```

**Comment by hondasmx** [comment]
Добрый день!

Спасибо за предложение, Обновим в ближайшей версии

**Comment by davalex1968** [comment]
Такая же проблема при попытке создать толстый жарник. Создается, но не запускается. Обычная JAVA, код взят из проекта invest-api-java-sdk-main v1.3. Из среды IDE все работает без проблем. 
ьрЁ. 25, 2023 8:27:53 AM io.grpc.NameResolverRegistry getDefaultRegistry
WARNING: No NameResolverProviders found via ServiceLoader, including for DNS. This is probably due to a broken build. If using ProGuard, check your configuration
Exception in thread "main" java.lang.NullPointerException: target
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
        at io.grpc.internal.ManagedChannelImplBuilder.<init>(ManagedChannelImplBuilder.java:247)
        at io.grpc.internal.ManagedChannelImplBuilder.<init>(ManagedChannelImplBuilder.java:232)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:195)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forTarget(NettyChannelBuilder.java:165)
        at ru.tinkoff.piapi.core.InvestApi.defaultChannel(InvestApi.java:244)
        at ru.tinkoff.piapi.core.InvestApi.defaultChannel(InvestApi.java:268)
        at ru.tinkoff.piapi.core.InvestApi.create(InvestApi.java:122)
        at modtrade.app.Start_Main.main(Start_Main.java:79)
